config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'lists#index'
  resources :lists, except: [:index] do
    resources :bookmarks, only: [:new, :create ]
  end
  resources :bookmarks, only: [:destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie


  validates :movie_id, uniqueness: { scope: :list_id,
    message: "the movie is already in the list" }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks 

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
   
  def new
    @list = List.find(params[:list_id])    
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
  
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

 

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id )
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, except: [ :index, :new, :create ]
  def index
    @lists = List.all
  end

  def show
    # @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else 
      render :new
    end
   
  end

  def edit
  end

  def update
    
    @list.update(list_params)
    if @list.save
      redirect_to list_path(@list)
    else 
      render :edit
    end
  end

  def destroy
    
    @list.destroy
    redirect_to root_path
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookmarkMovie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class='width-form border'>
  
    <%= simple_form_for(list)do |f| %>
      <%= f.input :name, input_html: { class: "color-input"}, label_html: { class: "color-label"} %>
      <%= f.input :photo, as: :file, input_html: { class: "color-input"}, label_html: { class: "color-label"} %>
      <%= f.submit class: "btn-submit" %>
    <% end %>
  
</div>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div class="banner-lists-index" >
  <a href="#lists" class=' create-btn link-to-lists'>Check My List</a>

</div>


<div class="container my-4 mx-auto">
  <div class="header-container" id='lists' >
    <h2>My Lists</h2>
    <%= link_to 'Create new list', new_list_path, class: "create-btn"  %>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-4" >
        <%= link_to list_path(list), class: "link-list" do %>
          <div class="list-card" style='background-image: url("<%= cl_image_path list.photo.key%>")'>
            
            <h2><%= list.name %></h2>  
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class="banner-show" style='background-image: url("<%= cl_image_path @list.photo.key%>")'>
       
      <h2><%= @list.name %></h2>  
</div>

<%= link_to 'back to lists', root_path %>
<%= link_to 'edit', edit_list_path %>
<%= link_to 'delete', list_path(@list),
                      method: :delete,
                      data: {confirm: 'are you sure?'}%>

<hr>
<%= link_to 'add movie', new_list_bookmark_path(@list) %>

<div class="bookmark-container">
    <% @list.movies.each do |movie| %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        
        <div class="movie_card">
        <%= image_tag "https://image.tmdb.org/t/p/w500#{movie.poster_url}", alt: movie.title, class: "movie-img rounded-top" %>
        <div class="movie-text">
            <h2><%= movie.title %></h2> 
            <p class='rating'><%= movie.rating %>⭐</p>
            <p><%= movie.overview %></p>
            <%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: {confirm: "are you sure you want to remove#{movie}"}%>
        </div> 
        </div>

    <% end %>
</div>


<%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: {confirm: "are you sure you want to remove#{movie}"}

app/views/shared/_banner.html.erb
<div class="banner-lists-index" >


</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo-container">
    <%= image_tag "https://toppng.com/uploads/preview/jpg-black-and-white-download-free-to-use-cliparts-transparent-background-popcorn-clipart-11562881064edjvi0xhso.png", alt: "alttext", class: "logo " %>
  </div>

  <div class="nav-link">
    <%= link_to "Lists", root_path, class: "nav-item" %>
    <%= link_to "Add list", new_list_path, class: "nav-item" %>
  </div>
</div>